-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 08:04:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hotel` (
  `id` INT NOT NULL,
  `hot_name` VARCHAR(45) NULL,
  `hot_type` VARCHAR(45) NULL,
  `hot_add` VARCHAR(255) NULL,
  `hot_cont` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`key`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`key` (
  `id` INT NOT NULL,
  `id` INT NULL,
  `key_holder` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room` (
  `id` INT NOT NULL,
  `room_type` VARCHAR(45) NOT NULL,
  `room_cpcty` INT NULL,
  `room_cont` INT(11) NOT NULL,
  `room_price` INT NOT NULL,
  `hotel_id` INT NOT NULL,
  `key_id` INT NOT NULL,
  PRIMARY KEY (`id`, `hotel_id`, `key_id`),
  INDEX `fk_room_hotel_idx` (`hotel_id` ASC) VISIBLE,
  INDEX `fk_room_key1_idx` (`key_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_hotel`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `mydb`.`hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_key1`
    FOREIGN KEY (`key_id`)
    REFERENCES `mydb`.`key` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bill` (
  `id` INT NOT NULL,
  `hot_name` VARCHAR(45) NOT NULL,
  `cus_fullname` VARCHAR(45) NOT NULL,
  `bill_dmg` INT NULL,
  `hotel_id` INT NOT NULL,
  PRIMARY KEY (`id`, `hotel_id`),
  INDEX `fk_bill_hotel1_idx` (`hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_bill_hotel1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `mydb`.`hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`check-in slip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`check-in slip` (
  `id` INT NOT NULL,
  `cus_fullname` VARCHAR(45) NOT NULL,
  `emp_fullname` VARCHAR(45) NOT NULL,
  `slip_cin` DATETIME NOT NULL,
  `slip_cout` DATETIME NOT NULL,
  `id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `employee_key_id` INT NOT NULL,
  `employee_customer_id` INT NOT NULL,
  `employee_customer_bill_id` INT NOT NULL,
  `employee_customer_bill_hotel_id` INT NOT NULL,
  PRIMARY KEY (`id`, `employee_id`, `employee_key_id`, `employee_customer_id`, `employee_customer_bill_id`, `employee_customer_bill_hotel_id`),
  INDEX `fk_check-in slip_employee1_idx` (`employee_id` ASC, `employee_key_id` ASC, `employee_customer_id` ASC, `employee_customer_bill_id` ASC, `employee_customer_bill_hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_check-in slip_employee1`
    FOREIGN KEY (`employee_id` , `employee_key_id` , `employee_customer_id` , `employee_customer_bill_id` , `employee_customer_bill_hotel_id`)
    REFERENCES `mydb`.`employee` (`id` , `key_id` , `customer_id` , `customer_bill_id` , `customer_bill_hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NOT NULL,
  `cus_fname` VARCHAR(45) NULL,
  `cus_lname` VARCHAR(45) NULL,
  `cus_initial` VARCHAR(45) NULL,
  `cus_fullname` VARCHAR(45) NOT NULL,
  `cus_add` VARCHAR(45) NOT NULL,
  `cus_cont` INT(11) NOT NULL,
  `cus_email` VARCHAR(45) NULL,
  `cus_crdt` INT NULL,
  `bill_id` INT NOT NULL,
  `bill_hotel_id` INT NOT NULL,
  `check-in slip_id` INT NOT NULL,
  `check-in slip_employee_id` INT NOT NULL,
  `check-in slip_employee_key_id` INT NOT NULL,
  `check-in slip_employee_customer_id` INT NOT NULL,
  `check-in slip_employee_customer_bill_id` INT NOT NULL,
  `check-in slip_employee_customer_bill_hotel_id` INT NOT NULL,
  PRIMARY KEY (`id`, `bill_id`, `bill_hotel_id`, `check-in slip_id`, `check-in slip_employee_id`, `check-in slip_employee_key_id`, `check-in slip_employee_customer_id`, `check-in slip_employee_customer_bill_id`, `check-in slip_employee_customer_bill_hotel_id`),
  INDEX `fk_customer_bill1_idx` (`bill_id` ASC, `bill_hotel_id` ASC) VISIBLE,
  INDEX `fk_customer_check-in slip1_idx` (`check-in slip_id` ASC, `check-in slip_employee_id` ASC, `check-in slip_employee_key_id` ASC, `check-in slip_employee_customer_id` ASC, `check-in slip_employee_customer_bill_id` ASC, `check-in slip_employee_customer_bill_hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_bill1`
    FOREIGN KEY (`bill_id` , `bill_hotel_id`)
    REFERENCES `mydb`.`bill` (`id` , `hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_check-in slip1`
    FOREIGN KEY (`check-in slip_id` , `check-in slip_employee_id` , `check-in slip_employee_key_id` , `check-in slip_employee_customer_id` , `check-in slip_employee_customer_bill_id` , `check-in slip_employee_customer_bill_hotel_id`)
    REFERENCES `mydb`.`check-in slip` (`id` , `employee_id` , `employee_key_id` , `employee_customer_id` , `employee_customer_bill_id` , `employee_customer_bill_hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT NOT NULL,
  `emp_fname` VARCHAR(45) NULL,
  `emp_lname` VARCHAR(45) NULL,
  `emp_initial` VARCHAR(45) NULL,
  `emp_fullname` VARCHAR(45) NOT NULL,
  `emp_add` VARCHAR(45) NOT NULL,
  `emp_cont` INT(11) NOT NULL,
  `emp_email` VARCHAR(45) NOT NULL,
  `emp_type` VARCHAR(45) NOT NULL,
  `key_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `customer_bill_id` INT NOT NULL,
  `customer_bill_hotel_id` INT NOT NULL,
  PRIMARY KEY (`id`, `key_id`, `customer_id`, `customer_bill_id`, `customer_bill_hotel_id`),
  INDEX `fk_employee_key1_idx` (`key_id` ASC) VISIBLE,
  INDEX `fk_employee_customer1_idx` (`customer_id` ASC, `customer_bill_id` ASC, `customer_bill_hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_key1`
    FOREIGN KEY (`key_id`)
    REFERENCES `mydb`.`key` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_customer1`
    FOREIGN KEY (`customer_id` , `customer_bill_id` , `customer_bill_hotel_id`)
    REFERENCES `mydb`.`customer` (`id` , `bill_id` , `bill_hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer_has_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer_has_room` (
  `customer_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `room_hotel_id` INT NOT NULL,
  `room_key_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `room_id`, `room_hotel_id`, `room_key_id`),
  INDEX `fk_customer_has_room_room1_idx` (`room_id` ASC, `room_hotel_id` ASC, `room_key_id` ASC) VISIBLE,
  INDEX `fk_customer_has_room_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_has_room_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_has_room_room1`
    FOREIGN KEY (`room_id` , `room_hotel_id` , `room_key_id`)
    REFERENCES `mydb`.`room` (`id` , `hotel_id` , `key_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
